/*
 * approx_exp_constants.h - Precomputed constants for ApproxExp
 *                          (Algorithm 1 of agent/ApproxExp/ApproxExp.tex).
 *
 * AUTO-GENERATED by gen_approx_exp_tables.py. DO NOT EDIT BY HAND.
 *
 *  Design parameters (Algorithm 1):
 *    BETA      = 5     -> B = 2^BETA = 32
 *    RCP shift = 57   -> RCP = floor((B/ln2) * 2^57)
 *    LB  shift = 69    -> LB  = round((ln2/B) * 2^(64+BETA)) = ((ln2/B) * 2^69)
 *    I   shift = 80   -> I   = floor(2^80 / (2*sigma^2))   per mode
 *
 *  Error budget (relative to exp(-a); see ApproxExp.tex Section 4):
 *    E_aq60   <= 2^-59   (Q80 reciprocal + 128-bit multiply)
 *    E_range  <= 2^-61   (m*LB plus Q(64+beta) -> Q64 shift)
 *    E_poly   <= 2^-61.31 (Sage Horner-aware fit on [31/32*ln2, ln2])
 *    E_table  <= 2^-63   (T[j] rounded to nearest Q63)
 *    E_mul    <= 2^-62   (one mulh64 truncation in Step 5)
 *    E_shift  <= 2^-64 / exp(-a)  (round-to-nearest output)
 *  Combined: 2^-58 (a-independent) + E_shift; worst-case a~7.37 -> 2^-53.3
 *  meeting the K=53 relative-precision target with ~0.3 bit margin.
 */

#ifndef SHUTTLE_APPROX_EXP_CONSTANTS_H
#define SHUTTLE_APPROX_EXP_CONSTANTS_H

#include <stdint.h>
#include "config.h"

/* Design parameters. Algorithm 1 of ApproxExp.tex.
 * Changing BETA propagates through TABLE_T size, RCP, LB and the
 * compile-time bit-shifts in approx_exp.c; the generator script ties
 * all of them together. */
#define APPROX_EXP_BETA   5
#define APPROX_EXP_B      (1u << APPROX_EXP_BETA)

/* RCP = floor((B / ln2) * 2^57). Used in Step 1 of approx_exp:
 *   V = mulh64(a_q60, APPROX_EXP_RCP) = floor((B*a/ln2) * 2^53)
 * Stored as a single uint64 since log2(RCP) ~ 62.5 < 64. */
#define APPROX_EXP_RCP_SHIFT  57
#define APPROX_EXP_RCP        UINT64_C(6653256548922161245)

/* LB = round((ln2 / B) * 2^(64+BETA)). Used in Step 2:
 *   R   = m * LB - (a_q60 << (BETA + 4))    [128-bit]
 *   X   = R >> BETA                          [Q64]
 * Stored as a single uint64 since log2(LB) ~ 63.47 < 64. */
#define APPROX_EXP_LB_SHIFT   69
#define APPROX_EXP_LB         UINT64_C(12786308645202655660)

/* Q63 table  T[j] = round(2^{-j/B} * 2^63),  j in 0..B-1.
 * Total: B * 8 = 256 bytes. Looked up in constant time by approx_exp.c. */
static const uint64_t APPROX_EXP_TABLE_T[APPROX_EXP_B] = {
    UINT64_C( 9223372036854775808), UINT64_C( 9025734193507008925), UINT64_C( 8832331321595618838), UINT64_C( 8643072674415606502),
    UINT64_C( 8457869449776733335), UINT64_C( 8276634748336579668), UINT64_C( 8099283532826439817), UINT64_C( 7925732588150922155),
    UINT64_C( 7755900482342532474), UINT64_C( 7589707528352920109), UINT64_C( 7427075746662858866), UINT64_C( 7267928828693418961),
    UINT64_C( 7112192101001162095), UINT64_C( 6959792490240559659), UINT64_C( 6810658488877194079), UINT64_C( 6664720121635655541),
    UINT64_C( 6521908912666391106), UINT64_C( 6382157853416100552), UINT64_C( 6245401371186603363), UINT64_C( 6111575298367424380),
    UINT64_C( 5980616842327661685), UINT64_C( 5852464555953009676), UINT64_C( 5727058308814112983), UINT64_C( 5604339258952723100),
    UINT64_C( 5484249825272419512), UINT64_C( 5366733660520940721), UINT64_C( 5251735624851448219), UINT64_C( 5139201759950318048),
    UINT64_C( 5029079263719320435), UINT64_C( 4921316465500308116), UINT64_C( 4815862801830788490), UINT64_C( 4712668792719003884),
};

/* ============================================================
 * Per-mode Q80 reciprocal of 2*sigma^2.
 *
 *   I = floor(2^80 / (2*sigma^2))  (~64..66 bits)
 *
 * The sampler computes the input a_q60 to approx_exp as:
 *   num   = y * (y + 2*k*x)                  -- fits in uint32 (<2^20)
 *   M_lo  = num * I_lo  (full 128-bit)
 *   M_hi  = num * I_hi  (always fits in uint64 since num < 2^20)
 *   a_q60 = (M_lo + (M_hi << 64)) >> 20      -- truncated to Q60
 *
 * Error analysis (Section 4.1 of ApproxExp.tex):
 *   I = 2^80/N - delta_I,  0 <= delta_I < 1
 *   M = num * I            (exact integer multiply)
 *   |M_ideal - M|     <= num <= 2^18      (in Q80 ULP)
 *   |a_q60 - a*2^60|  <= 2^18/2^20 + 1 = 5/4 + 1 < 2  (in Q60 ULP)
 *   |Delta a|         <= 2 / 2^60 = 2^{-59}
 *   |E_aq60|/exp(-a)  <= 2^{-59}
 * ============================================================ */

/* SHUTTLE-128: sigma = 101, 2*sigma^2 = 20402,  I has 66 bits. */
#if SHUTTLE_MODE == 128
#  define APPROX_EXP_I_HI  UINT64_C(3)
#  define APPROX_EXP_I_LO  UINT64_C(3915028028583587809)
#endif

/* SHUTTLE-256: sigma = 149, 2*sigma^2 = 44402,  I has 65 bits. */
#if SHUTTLE_MODE == 256
#  define APPROX_EXP_I_HI  UINT64_C(1)
#  define APPROX_EXP_I_LO  UINT64_C(8780088492720545557)
#endif

/* SHUTTLE-512: sigma = 202, 2*sigma^2 = 81608,  I has 64 bits. */
#if SHUTTLE_MODE == 512
#  define APPROX_EXP_I_HI  UINT64_C(0)
#  define APPROX_EXP_I_LO  UINT64_C(14813815062428060664)
#endif

#endif /* SHUTTLE_APPROX_EXP_CONSTANTS_H */
