/* SHUTTLE rANS frequency tables. Auto-generated by SHUTTLE/tools/gen_rans_tables.py — do not edit. */
#ifndef SHUTTLE_RANS_TABLES_H
#define SHUTTLE_RANS_TABLES_H
#include <stdint.h>

/* ================================================================ */
/* rANS hint h frequency table for SHUTTLE-128                   */
/* symbols: [-10, 10]  total 21, sum of freqs = 4096 */
/* ================================================================ */
#define SHUTTLE128_RANS_PROB_BITS 12
#define SHUTTLE128_RANS_SYM_MIN  (-10)
#define SHUTTLE128_RANS_SYM_MAX  (10)
#define SHUTTLE128_RANS_NUM_SYMS 21

static const int16_t shuttle128_rans_syms[21] = {
     -10,   -9,   -8,   -7,   -6,   -5,   -4,   -3,   -2,   -1,    0,    1,
       2,    3,    4,    5,    6,    7,    8,    9,   10,
};

static const uint16_t shuttle128_rans_freqs[21] = {
        1,     1,     1,     1,     1,     9,    50,   184,   473,   831,   992,   831,
      473,   184,    50,     9,     1,     1,     1,     1,     1,
};

/* ================================================================ */
/* rANS hint h frequency table for SHUTTLE-256                   */
/* symbols: [-8, 8]  total 17, sum of freqs = 4096 */
/* ================================================================ */
#define SHUTTLE256_RANS_PROB_BITS 12
#define SHUTTLE256_RANS_SYM_MIN  (-8)
#define SHUTTLE256_RANS_SYM_MAX  (8)
#define SHUTTLE256_RANS_NUM_SYMS 17

static const int16_t shuttle256_rans_syms[17] = {
      -8,   -7,   -6,   -5,   -4,   -3,   -2,   -1,    0,    1,    2,    3,
       4,    5,    6,    7,    8,
};

static const uint16_t shuttle256_rans_freqs[17] = {
        1,     1,     1,     1,     7,    68,   356,   954,  1318,   954,   356,    68,
        7,     1,     1,     1,     1,
};

/* ================================================================ */
/* rANS z[1..L] HighBits frequency table for SHUTTLE-128                   */
/* symbols: [-6, 6]  total 13, sum of freqs = 4096 */
/* ================================================================ */
#define SHUTTLE128_RANS_Z1_PROB_BITS 12
#define SHUTTLE128_RANS_Z1_SYM_MIN  (-6)
#define SHUTTLE128_RANS_Z1_SYM_MAX  (6)
#define SHUTTLE128_RANS_Z1_NUM_SYMS 13

static const int16_t shuttle128_rans_z1_syms[13] = {
      -6,   -5,   -4,   -3,   -2,   -1,    0,    1,    2,    3,    4,    5,
       6,
};

static const uint16_t shuttle128_rans_z1_freqs[13] = {
        1,     1,     1,     3,   115,   960,  1934,   960,   115,     3,     1,     1,
        1,
};

/* ================================================================ */
/* rANS z[1..L] HighBits frequency table for SHUTTLE-256                   */
/* symbols: [-5, 5]  total 11, sum of freqs = 4096 */
/* ================================================================ */
#define SHUTTLE256_RANS_Z1_PROB_BITS 12
#define SHUTTLE256_RANS_Z1_SYM_MIN  (-5)
#define SHUTTLE256_RANS_Z1_SYM_MAX  (5)
#define SHUTTLE256_RANS_Z1_NUM_SYMS 11

static const int16_t shuttle256_rans_z1_syms[11] = {
      -5,   -4,   -3,   -2,   -1,    0,    1,    2,    3,    4,    5,
};

static const uint16_t shuttle256_rans_z1_freqs[11] = {
        1,     1,     1,    20,   779,  2492,   779,    20,     1,     1,     1,
};

/* ================================================================ */
/* rANS Z_0 = CompressY(z^(0)) frequency table for SHUTTLE-128                   */
/* symbols: [-76, 76]  total 153, sum of freqs = 4096 */
/* ================================================================ */
#define SHUTTLE128_RANS_Z0_PROB_BITS 12
#define SHUTTLE128_RANS_Z0_SYM_MIN  (-76)
#define SHUTTLE128_RANS_Z0_SYM_MAX  (76)
#define SHUTTLE128_RANS_Z0_NUM_SYMS 153

static const int16_t shuttle128_rans_z0_syms[153] = {
     -76,  -75,  -74,  -73,  -72,  -71,  -70,  -69,  -68,  -67,  -66,  -65,
     -64,  -63,  -62,  -61,  -60,  -59,  -58,  -57,  -56,  -55,  -54,  -53,
     -52,  -51,  -50,  -49,  -48,  -47,  -46,  -45,  -44,  -43,  -42,  -41,
     -40,  -39,  -38,  -37,  -36,  -35,  -34,  -33,  -32,  -31,  -30,  -29,
     -28,  -27,  -26,  -25,  -24,  -23,  -22,  -21,  -20,  -19,  -18,  -17,
     -16,  -15,  -14,  -13,  -12,  -11,  -10,   -9,   -8,   -7,   -6,   -5,
      -4,   -3,   -2,   -1,    0,    1,    2,    3,    4,    5,    6,    7,
       8,    9,   10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
      20,   21,   22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
      32,   33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
      44,   45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
      56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,   67,
      68,   69,   70,   71,   72,   73,   74,   75,   76,
};

static const uint16_t shuttle128_rans_z0_freqs[153] = {
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     2,     2,     3,     3,     4,     5,     6,     8,     9,
       11,    13,    16,    18,    21,    24,    28,    33,    37,    42,    47,    53,
       58,    64,    70,    76,    82,    89,    95,   100,   105,   111,   116,   119,
      123,   126,   128,   128,    68,   128,   128,   126,   123,   119,   116,   111,
      105,   100,    95,    89,    82,    76,    70,    64,    58,    53,    47,    42,
       37,    33,    28,    24,    21,    18,    16,    13,    11,     9,     8,     6,
        5,     4,     3,     3,     2,     2,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     1,     1,     1,
};

/* ================================================================ */
/* rANS Z_0 = CompressY(z^(0)) frequency table for SHUTTLE-256                   */
/* symbols: [-58, 58]  total 117, sum of freqs = 4096 */
/* ================================================================ */
#define SHUTTLE256_RANS_Z0_PROB_BITS 12
#define SHUTTLE256_RANS_Z0_SYM_MIN  (-58)
#define SHUTTLE256_RANS_Z0_SYM_MAX  (58)
#define SHUTTLE256_RANS_Z0_NUM_SYMS 117

static const int16_t shuttle256_rans_z0_syms[117] = {
     -58,  -57,  -56,  -55,  -54,  -53,  -52,  -51,  -50,  -49,  -48,  -47,
     -46,  -45,  -44,  -43,  -42,  -41,  -40,  -39,  -38,  -37,  -36,  -35,
     -34,  -33,  -32,  -31,  -30,  -29,  -28,  -27,  -26,  -25,  -24,  -23,
     -22,  -21,  -20,  -19,  -18,  -17,  -16,  -15,  -14,  -13,  -12,  -11,
     -10,   -9,   -8,   -7,   -6,   -5,   -4,   -3,   -2,   -1,    0,    1,
       2,    3,    4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
      14,   15,   16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
      26,   27,   28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
      38,   39,   40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
      50,   51,   52,   53,   54,   55,   56,   57,   58,
};

static const uint16_t shuttle256_rans_z0_freqs[117] = {
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     2,     3,     4,     5,     6,     8,
       11,    14,    18,    22,    27,    33,    40,    48,    57,    66,    77,    88,
       99,   110,   121,   133,   143,   152,   160,   166,   172,   174,   118,   174,
      172,   166,   160,   152,   143,   133,   121,   110,    99,    88,    77,    66,
       57,    48,    40,    33,    27,    22,    18,    14,    11,     8,     6,     5,
        4,     3,     2,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     1,     1,     1,
};

/* ================================================================ */
/* SHUTTLE-512 tables.
 *
 * These are INITIAL placeholders generated by a one-shot Gaussian fit
 * (see gen_zetas.py history / project notes). They are NOT calibrated
 * to empirical signing distributions and must be rerun through
 * SHUTTLE/tools/calibrate_rans.py before final submission. Current
 * shapes:
 *   hint : Gaussian over [-8, 8],   sigma = 2.0
 *   z1   : Gaussian over [-5, 5],   sigma = 1.4
 *   z0   : Gaussian over [-100, 100], sigma = 13.0
 *
 * If a real signature attempt produces a value outside the symbol
 * range, the encoder returns OOV and the signer retries (slower but
 * still correct).
 * ================================================================ */

#define SHUTTLE512_RANS_PROB_BITS 12
#define SHUTTLE512_RANS_SYM_MIN  (-8)
#define SHUTTLE512_RANS_SYM_MAX  (8)
#define SHUTTLE512_RANS_NUM_SYMS 17

static const int16_t shuttle512_rans_syms[17] = {
       -8,    -7,    -6,    -5,    -4,    -3,    -2,    -1,     0,     1,     2,     3,
        4,     5,     6,     7,     8,
};

static const uint16_t shuttle512_rans_freqs[17] = {
        1,     2,     9,    36,   111,   265,   496,   719,   817,   720,   496,   265,
      111,    36,     9,     2,     1,
};

#define SHUTTLE512_RANS_Z1_PROB_BITS 12
#define SHUTTLE512_RANS_Z1_SYM_MIN  (-5)
#define SHUTTLE512_RANS_Z1_SYM_MAX  (5)
#define SHUTTLE512_RANS_Z1_NUM_SYMS 11

static const int16_t shuttle512_rans_z1_syms[11] = {
       -5,    -4,    -3,    -2,    -1,     0,     1,     2,     3,     4,     5,
};

static const uint16_t shuttle512_rans_z1_freqs[11] = {
        2,    20,   118,   421,   903,  1167,   904,   421,   118,    20,     2,
};

#define SHUTTLE512_RANS_Z0_PROB_BITS 12
#define SHUTTLE512_RANS_Z0_SYM_MIN  (-100)
#define SHUTTLE512_RANS_Z0_SYM_MAX  (100)
#define SHUTTLE512_RANS_Z0_NUM_SYMS 201

static const int16_t shuttle512_rans_z0_syms[201] = {
     -100,   -99,   -98,   -97,   -96,   -95,   -94,   -93,   -92,   -91,   -90,   -89,
      -88,   -87,   -86,   -85,   -84,   -83,   -82,   -81,   -80,   -79,   -78,   -77,
      -76,   -75,   -74,   -73,   -72,   -71,   -70,   -69,   -68,   -67,   -66,   -65,
      -64,   -63,   -62,   -61,   -60,   -59,   -58,   -57,   -56,   -55,   -54,   -53,
      -52,   -51,   -50,   -49,   -48,   -47,   -46,   -45,   -44,   -43,   -42,   -41,
      -40,   -39,   -38,   -37,   -36,   -35,   -34,   -33,   -32,   -31,   -30,   -29,
      -28,   -27,   -26,   -25,   -24,   -23,   -22,   -21,   -20,   -19,   -18,   -17,
      -16,   -15,   -14,   -13,   -12,   -11,   -10,    -9,    -8,    -7,    -6,    -5,
       -4,    -3,    -2,    -1,     0,     1,     2,     3,     4,     5,     6,     7,
        8,     9,    10,    11,    12,    13,    14,    15,    16,    17,    18,    19,
       20,    21,    22,    23,    24,    25,    26,    27,    28,    29,    30,    31,
       32,    33,    34,    35,    36,    37,    38,    39,    40,    41,    42,    43,
       44,    45,    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
       56,    57,    58,    59,    60,    61,    62,    63,    64,    65,    66,    67,
       68,    69,    70,    71,    72,    73,    74,    75,    76,    77,    78,    79,
       80,    81,    82,    83,    84,    85,    86,    87,    88,    89,    90,    91,
       92,    93,    94,    95,    96,    97,    98,    99,   100,
};

static const uint16_t shuttle512_rans_z0_freqs[201] = {
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     2,     2,     3,     3,     4,     5,     6,     7,     9,    10,
       12,    15,    17,    20,    23,    26,    30,    34,    38,    43,    48,    53,
       59,    65,    70,    76,    82,    88,    94,    99,   104,   109,   111,   111,
      111,   111,   111,   111,   126,   111,   111,   111,   111,   112,   112,   109,
      104,    99,    94,    88,    82,    76,    70,    65,    59,    53,    48,    43,
       38,    34,    30,    26,    23,    20,    17,    15,    12,    10,     9,     7,
        6,     5,     4,     3,     3,     2,     2,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     1,     1,     1,
};

#endif /* SHUTTLE_RANS_TABLES_H */
