/* SHUTTLE rANS frequency tables. Auto-generated by SHUTTLE/tools/gen_rans_tables.py — do not edit. */
#ifndef SHUTTLE_RANS_TABLES_H
#define SHUTTLE_RANS_TABLES_H
#include <stdint.h>

/* ================================================================ */
/* rANS hint h frequency table for SHUTTLE-128                   */
/* symbols: [-7, 7]  total 15, sum of freqs = 4096 */
/* ================================================================ */
#define SHUTTLE128_RANS_PROB_BITS 12
#define SHUTTLE128_RANS_SYM_MIN  (-7)
#define SHUTTLE128_RANS_SYM_MAX  (7)
#define SHUTTLE128_RANS_NUM_SYMS 15

static const int16_t shuttle128_rans_syms[15] = {
      -7,   -6,   -5,   -4,   -3,   -2,   -1,    0,    1,    2,    3,    4,
       5,    6,    7,
};

static const uint16_t shuttle128_rans_freqs[15] = {
        1,     1,     9,    50,   183,   474,   830,  1000,   830,   474,   183,    50,
        9,     1,     1,
};

/* ================================================================ */
/* rANS hint h frequency table for SHUTTLE-256                   */
/* symbols: [-6, 6]  total 13, sum of freqs = 4096 */
/* ================================================================ */
#define SHUTTLE256_RANS_PROB_BITS 12
#define SHUTTLE256_RANS_SYM_MIN  (-6)
#define SHUTTLE256_RANS_SYM_MAX  (6)
#define SHUTTLE256_RANS_NUM_SYMS 13

static const int16_t shuttle256_rans_syms[13] = {
      -6,   -5,   -4,   -3,   -2,   -1,    0,    1,    2,    3,    4,    5,
       6,
};

static const uint16_t shuttle256_rans_freqs[13] = {
        1,     1,     7,    68,   354,   954,  1326,   954,   354,    68,     7,     1,
        1,
};

/* ================================================================ */
/* rANS z[1..L] HighBits frequency table for SHUTTLE-128                   */
/* symbols: [-4, 4]  total 9, sum of freqs = 4096 */
/* ================================================================ */
#define SHUTTLE128_RANS_Z1_PROB_BITS 12
#define SHUTTLE128_RANS_Z1_SYM_MIN  (-4)
#define SHUTTLE128_RANS_Z1_SYM_MAX  (4)
#define SHUTTLE128_RANS_Z1_NUM_SYMS 9

static const int16_t shuttle128_rans_z1_syms[9] = {
      -4,   -3,   -2,   -1,    0,    1,    2,    3,    4,
};

static const uint16_t shuttle128_rans_z1_freqs[9] = {
        1,     3,   116,   958,  1940,   958,   116,     3,     1,
};

/* ================================================================ */
/* rANS z[1..L] HighBits frequency table for SHUTTLE-256                   */
/* symbols: [-3, 3]  total 7, sum of freqs = 4096 */
/* ================================================================ */
#define SHUTTLE256_RANS_Z1_PROB_BITS 12
#define SHUTTLE256_RANS_Z1_SYM_MIN  (-3)
#define SHUTTLE256_RANS_Z1_SYM_MAX  (3)
#define SHUTTLE256_RANS_Z1_NUM_SYMS 7

static const int16_t shuttle256_rans_z1_syms[7] = {
      -3,   -2,   -1,    0,    1,    2,    3,
};

static const uint16_t shuttle256_rans_z1_freqs[7] = {
        1,    20,   779,  2496,   779,    20,     1,
};

/* ================================================================ */
/* rANS Z_0 = CompressY(z^(0)) frequency table for SHUTTLE-128                   */
/* symbols: [-62, 62]  total 125, sum of freqs = 4096 */
/* ================================================================ */
#define SHUTTLE128_RANS_Z0_PROB_BITS 12
#define SHUTTLE128_RANS_Z0_SYM_MIN  (-62)
#define SHUTTLE128_RANS_Z0_SYM_MAX  (62)
#define SHUTTLE128_RANS_Z0_NUM_SYMS 125

static const int16_t shuttle128_rans_z0_syms[125] = {
     -62,  -61,  -60,  -59,  -58,  -57,  -56,  -55,  -54,  -53,  -52,  -51,
     -50,  -49,  -48,  -47,  -46,  -45,  -44,  -43,  -42,  -41,  -40,  -39,
     -38,  -37,  -36,  -35,  -34,  -33,  -32,  -31,  -30,  -29,  -28,  -27,
     -26,  -25,  -24,  -23,  -22,  -21,  -20,  -19,  -18,  -17,  -16,  -15,
     -14,  -13,  -12,  -11,  -10,   -9,   -8,   -7,   -6,   -5,   -4,   -3,
      -2,   -1,    0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
      10,   11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
      22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
      34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
      46,   47,   48,   49,   50,   51,   52,   53,   54,   55,   56,   57,
      58,   59,   60,   61,   62,
};

static const uint16_t shuttle128_rans_z0_freqs[125] = {
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     2,     2,     2,     3,     4,     5,     7,     7,    10,    11,    13,
       15,    19,    21,    24,    29,    33,    35,    42,    46,    53,    57,    64,
       69,    74,    82,    90,    97,   102,   104,   108,   115,   122,   125,   127,
      128,   125,   102,   125,   128,   127,   125,   122,   115,   108,   104,   102,
       97,    90,    82,    74,    69,    64,    57,    53,    46,    42,    35,    33,
       29,    24,    21,    19,    15,    13,    11,    10,     7,     7,     5,     4,
        3,     2,     2,     2,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,
};

/* ================================================================ */
/* rANS Z_0 = CompressY(z^(0)) frequency table for SHUTTLE-256                   */
/* symbols: [-46, 46]  total 93, sum of freqs = 4096 */
/* ================================================================ */
#define SHUTTLE256_RANS_Z0_PROB_BITS 12
#define SHUTTLE256_RANS_Z0_SYM_MIN  (-46)
#define SHUTTLE256_RANS_Z0_SYM_MAX  (46)
#define SHUTTLE256_RANS_Z0_NUM_SYMS 93

static const int16_t shuttle256_rans_z0_syms[93] = {
     -46,  -45,  -44,  -43,  -42,  -41,  -40,  -39,  -38,  -37,  -36,  -35,
     -34,  -33,  -32,  -31,  -30,  -29,  -28,  -27,  -26,  -25,  -24,  -23,
     -22,  -21,  -20,  -19,  -18,  -17,  -16,  -15,  -14,  -13,  -12,  -11,
     -10,   -9,   -8,   -7,   -6,   -5,   -4,   -3,   -2,   -1,    0,    1,
       2,    3,    4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
      14,   15,   16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
      26,   27,   28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
      38,   39,   40,   41,   42,   43,   44,   45,   46,
};

static const uint16_t shuttle256_rans_z0_freqs[93] = {
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     2,     3,     4,     4,     6,     8,
       10,    15,    18,    22,    27,    34,    40,    48,    57,    66,    76,    87,
       97,   111,   122,   136,   139,   148,   162,   171,   170,   173,   148,   173,
      170,   171,   162,   148,   139,   136,   122,   111,    97,    87,    76,    66,
       57,    48,    40,    34,    27,    22,    18,    15,    10,     8,     6,     4,
        4,     3,     2,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     1,     1,     1,
};

#endif /* SHUTTLE_RANS_TABLES_H */
