/* SHUTTLE rANS frequency tables.
 * Auto-generated by SHUTTLE/tools/gen_rans_tables.py.
 *
 * Tables come from the theoretical discrete Gaussian PMF.
 * The alphabet is the |y|_inf <= 11*sigma tight bound (Cor 3 / Thm 5
 * / Thm 7 of SHUTTLE_rANS.tex), so no signature coefficient can fall
 * outside the vocabulary; OOV is mathematically impossible.
 *
 * Two contexts per mode in general:
 *   z-hi  : carries HighBits_{alpha_0'}(z^(0)) and HighBits_{alpha_r}(z^(1..lenS))
 *   hint  : carries the MakeHint output
 * For mode-128 alpha_h == 2*alpha_r, so sigma_hint == sigma_zhi and a
 * single shared table is emitted (named *_unified) as well as redirect
 * macros that point the {zhi,hint} names at the same data.
 *
 * Do not edit by hand — regenerate with:
 *   python3 SHUTTLE/tools/gen_rans_tables.py --out SHUTTLE/ref/rans_tables.h
 */
#ifndef SHUTTLE_RANS_TABLES_H
#define SHUTTLE_RANS_TABLES_H
#include <stdint.h>

/* ================================================================ */
/* SHUTTLE-128 rANS unified frequency table.                 */
/*   sigma = 1.5781, M_voc = 18 (alphabet [-M_voc, M_voc]) */
/*   prob_bits = 10, sum(freqs) = 1024.                */
/* Generated by tools/gen_rans_tables.py from the theoretical PMF.    */
/* See SHUTTLE_rANS.tex §2.3 (PMF) and §3 (M_voc tight bound).        */
/* ================================================================ */
#define SHUTTLE128_RANS_UNIFIED_PROB_BITS 10
#define SHUTTLE128_RANS_UNIFIED_SYM_MIN  (-18)
#define SHUTTLE128_RANS_UNIFIED_SYM_MAX  (18)
#define SHUTTLE128_RANS_UNIFIED_NUM_SYMS 37

static const int16_t shuttle128_rans_unified_syms[37] = {
     -18,  -17,  -16,  -15,  -14,  -13,  -12,  -11,  -10,   -9,   -8,   -7,
      -6,   -5,   -4,   -3,   -2,   -1,    0,    1,    2,    3,    4,    5,
       6,    7,    8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
      18,
};

static const uint16_t shuttle128_rans_unified_freqs[37] = {
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     2,    10,    42,   116,   212,   234,   212,   116,    42,    10,     2,
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,
};

/* mode-128 coincidence: sigma_hint == sigma_zhi, both contexts
 * share the unified table above. */
#define SHUTTLE128_RANS_ZHI_PROB_BITS  SHUTTLE128_RANS_UNIFIED_PROB_BITS
#define SHUTTLE128_RANS_ZHI_SYM_MIN  SHUTTLE128_RANS_UNIFIED_SYM_MIN
#define SHUTTLE128_RANS_ZHI_SYM_MAX  SHUTTLE128_RANS_UNIFIED_SYM_MAX
#define SHUTTLE128_RANS_ZHI_NUM_SYMS  SHUTTLE128_RANS_UNIFIED_NUM_SYMS
#define SHUTTLE128_RANS_HINT_PROB_BITS SHUTTLE128_RANS_UNIFIED_PROB_BITS
#define SHUTTLE128_RANS_HINT_SYM_MIN SHUTTLE128_RANS_UNIFIED_SYM_MIN
#define SHUTTLE128_RANS_HINT_SYM_MAX SHUTTLE128_RANS_UNIFIED_SYM_MAX
#define SHUTTLE128_RANS_HINT_NUM_SYMS SHUTTLE128_RANS_UNIFIED_NUM_SYMS
#define shuttle128_rans_zhi_syms   shuttle128_rans_unified_syms
#define shuttle128_rans_zhi_freqs  shuttle128_rans_unified_freqs
#define shuttle128_rans_hint_syms  shuttle128_rans_unified_syms
#define shuttle128_rans_hint_freqs shuttle128_rans_unified_freqs

/* ================================================================ */
/* SHUTTLE-256 rANS zhi frequency table.                 */
/*   sigma = 2.3281, M_voc = 27 (alphabet [-M_voc, M_voc]) */
/*   prob_bits = 10, sum(freqs) = 1024.                */
/* Generated by tools/gen_rans_tables.py from the theoretical PMF.    */
/* See SHUTTLE_rANS.tex §2.3 (PMF) and §3 (M_voc tight bound).        */
/* ================================================================ */
#define SHUTTLE256_RANS_ZHI_PROB_BITS 10
#define SHUTTLE256_RANS_ZHI_SYM_MIN  (-27)
#define SHUTTLE256_RANS_ZHI_SYM_MAX  (27)
#define SHUTTLE256_RANS_ZHI_NUM_SYMS 55

static const int16_t shuttle256_rans_zhi_syms[55] = {
     -27,  -26,  -25,  -24,  -23,  -22,  -21,  -20,  -19,  -18,  -17,  -16,
     -15,  -14,  -13,  -12,  -11,  -10,   -9,   -8,   -7,   -6,   -5,   -4,
      -3,   -2,   -1,    0,    1,    2,    3,    4,    5,    6,    7,    8,
       9,   10,   11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
      21,   22,   23,   24,   25,   26,   27,
};

static const uint16_t shuttle256_rans_zhi_freqs[55] = {
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     1,     1,     2,     6,    17,    40,
       76,   121,   160,   140,   160,   121,    76,    40,    17,     6,     2,     1,
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     1,
};

/* ================================================================ */
/* SHUTTLE-256 rANS hint frequency table.                 */
/*   sigma = 0.2910, M_voc = 4 (alphabet [-M_voc, M_voc]) */
/*   prob_bits = 10, sum(freqs) = 1024.                */
/* Generated by tools/gen_rans_tables.py from the theoretical PMF.    */
/* See SHUTTLE_rANS.tex §2.3 (PMF) and §3 (M_voc tight bound).        */
/* ================================================================ */
#define SHUTTLE256_RANS_HINT_PROB_BITS 10
#define SHUTTLE256_RANS_HINT_SYM_MIN  (-4)
#define SHUTTLE256_RANS_HINT_SYM_MAX  (4)
#define SHUTTLE256_RANS_HINT_NUM_SYMS 9

static const int16_t shuttle256_rans_hint_syms[9] = {
      -4,   -3,   -2,   -1,    0,    1,    2,    3,    4,
};

static const uint16_t shuttle256_rans_hint_freqs[9] = {
        1,     1,     1,     3,  1012,     3,     1,     1,     1,
};

/* ================================================================ */
/* SHUTTLE-512 rANS zhi frequency table.                 */
/*   sigma = 3.1562, M_voc = 37 (alphabet [-M_voc, M_voc]) */
/*   prob_bits = 10, sum(freqs) = 1024.                */
/* Generated by tools/gen_rans_tables.py from the theoretical PMF.    */
/* See SHUTTLE_rANS.tex §2.3 (PMF) and §3 (M_voc tight bound).        */
/* ================================================================ */
#define SHUTTLE512_RANS_ZHI_PROB_BITS 10
#define SHUTTLE512_RANS_ZHI_SYM_MIN  (-37)
#define SHUTTLE512_RANS_ZHI_SYM_MAX  (37)
#define SHUTTLE512_RANS_ZHI_NUM_SYMS 75

static const int16_t shuttle512_rans_zhi_syms[75] = {
     -37,  -36,  -35,  -34,  -33,  -32,  -31,  -30,  -29,  -28,  -27,  -26,
     -25,  -24,  -23,  -22,  -21,  -20,  -19,  -18,  -17,  -16,  -15,  -14,
     -13,  -12,  -11,  -10,   -9,   -8,   -7,   -6,   -5,   -4,   -3,   -2,
      -1,    0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
      11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
      23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
      35,   36,   37,
};

static const uint16_t shuttle512_rans_zhi_freqs[75] = {
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     2,     5,    11,    21,    37,    58,    82,   106,
      123,    78,   123,   106,    82,    58,    37,    21,    11,     5,     2,     1,
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
        1,     1,     1,
};

/* ================================================================ */
/* SHUTTLE-512 rANS hint frequency table.                 */
/*   sigma = 0.1973, M_voc = 3 (alphabet [-M_voc, M_voc]) */
/*   prob_bits = 10, sum(freqs) = 1024.                */
/* Generated by tools/gen_rans_tables.py from the theoretical PMF.    */
/* See SHUTTLE_rANS.tex §2.3 (PMF) and §3 (M_voc tight bound).        */
/* ================================================================ */
#define SHUTTLE512_RANS_HINT_PROB_BITS 10
#define SHUTTLE512_RANS_HINT_SYM_MIN  (-3)
#define SHUTTLE512_RANS_HINT_SYM_MAX  (3)
#define SHUTTLE512_RANS_HINT_NUM_SYMS 7

static const int16_t shuttle512_rans_hint_syms[7] = {
      -3,   -2,   -1,    0,    1,    2,    3,
};

static const uint16_t shuttle512_rans_hint_freqs[7] = {
        1,     1,     1,  1018,     1,     1,     1,
};

#endif /* SHUTTLE_RANS_TABLES_H */
