/*
 * shuttle_rans.h - C-side rANS encoder/decoder for SHUTTLE hint & z1 compression.
 *
 * Mirrors SHUTTLE/tools/rans.py. Byte-wise renormalization, 32-bit state,
 * L = 2^23, compatible with Fabian Giesen's rANS_byte (same convention
 * used by HAETAE).
 *
 * Two frequency-table flavors are supported:
 *
 *   - "hint": distribution of the mod-2(q-1) signed hint h (used by Alg 2,
 *     Phase 6b). Default legacy API --- shuttle_rans_encode / shuttle_rans_decode.
 *
 *   - "z1":   distribution of HighBits(z[1..L]) = round(z / alpha_h), used
 *     by Phase 6c to split z[1..L] into a uniform low part + rANS-compressed
 *     high part.  API --- shuttle_rans_encode_z1 / shuttle_rans_decode_z1.
 *
 * Tables are sourced from rans_tables.h (auto-generated by
 * SHUTTLE/tools/gen_rans_tables.py) and selected at compile time via
 * SHUTTLE_MODE.
 *
 * All encode APIs may fail if any input symbol falls outside the selected
 * table's vocabulary; callers must treat this as a signing-round rejection
 * (restart IRS loop with fresh randomness). Decoders may fail if the byte
 * stream is truncated.
 */

#ifndef SHUTTLE_RANS_H
#define SHUTTLE_RANS_H

#include <stddef.h>
#include <stdint.h>

#include "params.h"

/* Renorm threshold (shared across modes and tables). */
#define SHUTTLE_RANS_L       (1u << 23)
#define SHUTTLE_RANS_BYTE_BITS  8

/*************************************************
* Name:        shuttle_rans_encode
*
* Description: Encode a sequence of n signed-integer symbols into the
*              output buffer using the HINT frequency table for the active
*              SHUTTLE_MODE. On success writes (*out_len) bytes.
*
*              rANS output length is data-dependent (2.3-2.8 bits/symbol
*              on typical SHUTTLE hint distributions). Callers must pass a
*              buffer of at least max_bytes >= ceil(n * prob_bits / 8) + 4
*              as a safe upper bound.
*
* Returns 0 on success;
*         -1 if a symbol is outside the table's vocabulary;
*         -2 if the output would exceed max_bytes.
**************************************************/
#define shuttle_rans_encode SHUTTLE_NAMESPACE(shuttle_rans_encode)
int shuttle_rans_encode(uint8_t *out, size_t *out_len, size_t max_bytes,
                        const int32_t *syms, size_t n);

/*************************************************
* Name:        shuttle_rans_decode
*
* Description: Decode n symbols from the byte stream using the HINT table.
*              Reads exactly in_len bytes. Callers MUST validate
*              authenticity before trusting decoded values.
*
* Returns 0 on success; -1 on underflow.
**************************************************/
#define shuttle_rans_decode SHUTTLE_NAMESPACE(shuttle_rans_decode)
int shuttle_rans_decode(int32_t *syms, size_t n,
                        const uint8_t *in, size_t in_len);

/*************************************************
* Name:        shuttle_rans_encode_z1 / shuttle_rans_decode_z1
*
* Description: Same contract as shuttle_rans_encode / _decode but using
*              the z[1..L] HighBits frequency table (Phase 6c). Expected
*              rate is ~1.4-1.8 bits/symbol, so a safe output bound is
*              ceil(n * prob_bits / 8) + 4.
**************************************************/
#define shuttle_rans_encode_z1 SHUTTLE_NAMESPACE(shuttle_rans_encode_z1)
int shuttle_rans_encode_z1(uint8_t *out, size_t *out_len, size_t max_bytes,
                           const int32_t *syms, size_t n);

#define shuttle_rans_decode_z1 SHUTTLE_NAMESPACE(shuttle_rans_decode_z1)
int shuttle_rans_decode_z1(int32_t *syms, size_t n,
                           const uint8_t *in, size_t in_len);

#endif /* SHUTTLE_RANS_H */
