/*
 * shuttle_rans.h - C-side rANS encoder/decoder for SHUTTLE signature
 *                  compression.
 *
 * ============================================================
 * Design rationale
 * ============================================================
 *
 * A SHUTTLE signature carries three vectors whose coefficients follow
 * (approximately) discrete Gaussian distributions:
 *
 *   Z_0   = CompressY(z^(0))           n coefficients, sigma ~ sigma/alpha_1
 *   hi_i  = HighBits_alpha_h(z^(i))    L*n coefficients, sigma ~ sigma/alpha_h
 *   h     = MakeHint output            M*n coefficients, sigma ~ 2*sigma/alpha_h
 *
 * Naive fixed-width packing wastes ~half the bits; Shannon says each slot
 * costs at most 0.5*log2(2*pi*e*sigma^2) bits, and rANS reaches this floor
 * with a sub-1% quantization overhead. That saving is what lets SHUTTLE
 * hit a ~1.3 KB / ~2.6 KB signature (see docs/NGCC_Sign/SHUTTLE_rANS_analysis.md).
 *
 * Why three tables, not one
 * -------------------------
 * The three vectors have *different* distributions (different sigma_eff and
 * different post-rounding shapes), so a single table would incur a large
 * cross-entropy penalty. Three pre-trained tables, each matching its vector,
 * keeps the per-coef overhead below ~0.02 bit.
 *
 * Why hi/lo split on z[1..L] but not on Z_0 or h
 * ----------------------------------------------
 * For z[1..L] the raw coef range is ~T_sigma*sigma + tau*eta (>1000 values);
 * a direct-rANS table would need a huge CDF. We instead split each z into
 *
 *     z = alpha_h * hi + lo,     lo in [-alpha_h/2, alpha_h/2)
 *
 * rANS-code `hi` (narrow vocabulary, ~9 symbols) and bit-pack `lo` uniformly
 * at log2(alpha_h) bits/coef. The split is entropy-lossless (prop. 2 of the
 * analysis doc) but collapses the rANS vocab by 2-3 orders of magnitude.
 *
 * Z_0 and h already have narrow vocabularies (~100 / ~15 symbols) so direct
 * rANS is fine -- the split would only add code complexity, not bytes.
 *
 * Failure modes and the IRS retry loop
 * ------------------------------------
 * Each encode call can fail in two ways:
 *   - OOV   : a coefficient falls outside the trained vocabulary => rc=-1
 *   - Overflow: the compressed stream exceeds the reserved budget => rc=-2
 * Both are per-signing-round rejections. sign.c:crypto_sign_signature
 * sees rc!=0 from pack_sig and restarts the IRS loop with fresh randomness.
 * This adds multiplicatively to the IRS rejection rate; we budget it to
 * stay negligible.
 *
 * Budget allocation (see params.h::SHUTTLE_*_RESERVED_BYTES)
 *   per-block p_ovf = p_OOV = 2^{-21}  =>  per-block fail = 2^{-20}
 *   per-sig total rANS fail ~ 3 * 2^{-20} = 2^{-18.4}
 * With p_IRS ~ 0.5, the throughput hit from rANS rejections is < 10^{-5} --
 * invisible in practice, but tight enough to shave ~140 B / ~190 B off the
 * signatures compared to a 2^{-100}-style overly-conservative budget.
 *
 * Calibration pipeline
 * --------------------
 * Per-block p_OOV target drives rANS vocab half-width M (via eq. 23 of
 * the analysis doc); per-block p_ovf target drives the reserved-byte size
 * (via eq. 20 with an empirical mu/sigma fit). Both are recomputed by
 *
 *     SHUTTLE/tools/sample_{hints,z0,z1}.py   (empirical histograms)
 *     SHUTTLE/tools/gen_rans_tables.py --p-oov ...   (vocab + freq table)
 *     SHUTTLE/tools/calibrate_rans.py   --p-ovf ...  (reserved bytes)
 *
 * Tables live in rans_tables.h; reservation budgets in params.h.
 *
 * ============================================================
 * Engine conventions
 * ============================================================
 *
 * Byte-wise renormalization, 32-bit state, L = 2^23. Compatible with
 * Fabian Giesen's rANS_byte, which is also what HAETAE ships. The pure
 * Python reference is SHUTTLE/tools/rans.py.
 *
 * Tables are sourced from rans_tables.h (auto-generated by
 * gen_rans_tables.py) and selected at compile time via SHUTTLE_MODE.
 *
 * Two API families (both use the same core engine):
 *   - shuttle_rans_encode / _decode      : hint h table
 *   - shuttle_rans_encode_z1 / _decode_z1: HighBits(z[1..L]) table
 *   - shuttle_rans_encode_z0 / _decode_z0: Z_0 = CompressY(z^(0)) table
 */

#ifndef SHUTTLE_RANS_H
#define SHUTTLE_RANS_H

#include <stddef.h>
#include <stdint.h>

#include "params.h"

/* Renorm threshold (shared across modes and tables). */
#define SHUTTLE_RANS_L       (1u << 23)
#define SHUTTLE_RANS_BYTE_BITS  8

/* Encode/decode contracts (shared across all three flavors)
 *
 * Encoders write (*out_len) bytes on success; caller must supply at least
 * SHUTTLE_*_RESERVED_BYTES for each flavor (see params.h). Returns:
 *    0  on success
 *   -1  if any input symbol is outside the table's vocabulary (OOV)
 *   -2  if the compressed stream would exceed max_bytes (overflow)
 * Both failure returns must be handled by the caller as signing-round
 * rejections (restart IRS with fresh randomness).
 *
 * Decoders read exactly in_len bytes; return 0 on success, -1 on
 * underflow. Callers MUST validate signature authenticity before
 * trusting decoded values.
 */
#define shuttle_rans_encode SHUTTLE_NAMESPACE(shuttle_rans_encode)
int shuttle_rans_encode(uint8_t *out, size_t *out_len, size_t max_bytes,
                        const int32_t *syms, size_t n);

#define shuttle_rans_decode SHUTTLE_NAMESPACE(shuttle_rans_decode)
int shuttle_rans_decode(int32_t *syms, size_t n,
                        const uint8_t *in, size_t in_len);

#define shuttle_rans_encode_z1 SHUTTLE_NAMESPACE(shuttle_rans_encode_z1)
int shuttle_rans_encode_z1(uint8_t *out, size_t *out_len, size_t max_bytes,
                           const int32_t *syms, size_t n);

#define shuttle_rans_decode_z1 SHUTTLE_NAMESPACE(shuttle_rans_decode_z1)
int shuttle_rans_decode_z1(int32_t *syms, size_t n,
                           const uint8_t *in, size_t in_len);

#define shuttle_rans_encode_z0 SHUTTLE_NAMESPACE(shuttle_rans_encode_z0)
int shuttle_rans_encode_z0(uint8_t *out, size_t *out_len, size_t max_bytes,
                           const int32_t *syms, size_t n);

#define shuttle_rans_decode_z0 SHUTTLE_NAMESPACE(shuttle_rans_decode_z0)
int shuttle_rans_decode_z0(int32_t *syms, size_t n,
                           const uint8_t *in, size_t in_len);

#endif /* SHUTTLE_RANS_H */
