/*
 * sign_v2.h - NGCC-Signature Alg 2 compressed signature scheme.
 *
 * Parallel implementation to Phase 6a (sign.c). Keys generated by v2 are
 * NOT compatible with Phase 6a verify (pk has different semantics; see
 * compute_b_v2 in polyvec.c). v2 is opt-in via the _v2 suffix in public
 * API, and the Phase 6a functions keep working unchanged.
 *
 * Sizes:
 *   SHUTTLE_PUBLICKEYBYTES  (unchanged, same as Phase 6a)
 *   SHUTTLE_SECRETKEYBYTES  (unchanged)
 *   SHUTTLE_BYTES_V2        (new, defined in packing_v2.h)
 */

#ifndef SHUTTLE_SIGN_V2_H
#define SHUTTLE_SIGN_V2_H

#include <stddef.h>
#include <stdint.h>

#include "params.h"
#include "packing_v2.h"

#define crypto_sign_keypair_v2   SHUTTLE_NAMESPACE(keypair_v2)
int crypto_sign_keypair_v2(uint8_t *pk, uint8_t *sk);

#define crypto_sign_signature_v2 SHUTTLE_NAMESPACE(signature_v2)
int crypto_sign_signature_v2(uint8_t *sig, size_t *siglen,
                             const uint8_t *m, size_t mlen,
                             const uint8_t *sk);

#define crypto_sign_verify_v2    SHUTTLE_NAMESPACE(verify_v2)
int crypto_sign_verify_v2(const uint8_t *sig, size_t siglen,
                          const uint8_t *m, size_t mlen,
                          const uint8_t *pk);

#define crypto_sign_v2           SHUTTLE_NAMESPACE(sign_v2)
int crypto_sign_v2(uint8_t *sm, size_t *smlen,
                   const uint8_t *m, size_t mlen,
                   const uint8_t *sk);

#define crypto_sign_open_v2      SHUTTLE_NAMESPACE(open_v2)
int crypto_sign_open_v2(uint8_t *m, size_t *mlen,
                        const uint8_t *sm, size_t smlen,
                        const uint8_t *pk);

#endif /* SHUTTLE_SIGN_V2_H */
