#!/usr/bin/env python3
"""gen_rounding.py - division-free round-to-nearest (ties-away-from-zero) magic
reciprocals for SHUTTLE CompressY, plus the alpha_h highbits shift constants.

CompressY divides each y-block by a positive divisor alpha in {alpha_1, alpha_s,
alpha_e} = {90/135/144, 10/5/3, 5/5/3} (NOT powers of two), ROUNDING to nearest
with TIES AWAY FROM ZERO (Description.tex:65).  These divides act on
SECRET-derived data (the uncompressed response), so NO hardware idiv / `% const`
is allowed.

The branchless ties-away kernel computes |v|, an unsigned round-divide, then
re-signs:

    m    = v >> 31                     # arithmetic sign mask, -1 if v<0
    av   = (v ^ m) - m                 # |v|
    qabs = (av*RECIP + ROUND_BIAS) >> SHIFT   # == floor((|v| + alpha/2)/alpha)
    res  = (qabs ^ m) - m              # re-sign

where, for ties-away-from-zero on |v|:
    floor((|v| + alpha/2) / alpha)        when alpha is EVEN, and
    floor((2*|v| + alpha) / (2*alpha))    when alpha is ODD
(both expressed as floor((|v| + floor(alpha/2) + (alpha&1 ? 0:0))/alpha) with the
right half-integer tie -- see below).  Concretely we want, for every integer
|v| >= 0,
    round_half_away(|v|/alpha) = floor( (2|v| + alpha) / (2 alpha) ).
We realize floor(P/D) with D = 2*alpha (and P = 2|v| + alpha) by a magic
reciprocal RECIP = ceil(2^SHIFT / D) so that
    floor(P/D) == (P * RECIP) >> SHIFT     for all P in [0, P_MAX].
We fold the +alpha bias into ROUND_BIAS = alpha*RECIP so the C kernel multiplies
only by |v| once:  qabs = (2*|v|*RECIP + ROUND_BIAS) >> SHIFT.

Reachable |v|: the CompressY input is the uncompressed response coeff, |v| well
under 2^20.  We PROVE exactness for every |v| in [0, 2^20) against Python's
round_half_away.  SHIFT is chosen as the smallest shift that is (i) exact over
that range and (ii) keeps 2*|v|*RECIP + ROUND_BIAS < 2^63 (the C kernel uses
int64 for the product).

alpha_h (1024/1024/2048) is a power of two -> highbits is a +alpha_h/2 bias then
a right shift by LOG2_ALPHA_H; no magic needed (emitted as a sanity static
assert only).

Emits: ../tools/rounding_consts.h  (included by ref/rounding.c via -I../tools).
Run:  python3 gen_rounding.py
"""

import os

VMAX = 1 << 20  # prove exact for |v| < 2^20 (>> any reachable response coeff)


def round_half_away(v, alpha):
    """Round v/alpha to nearest, ties away from zero, for v >= 0 integer."""
    # floor((2v + alpha) / (2 alpha))
    return (2 * v + alpha) // (2 * alpha)


def find_magic(alpha):
    """Return (RECIP, SHIFT, ROUND_BIAS) s.t. for all 0<=v<VMAX,
    (2*v*RECIP + ROUND_BIAS) >> SHIFT == round_half_away(v, alpha),
    with the product staying < 2^63."""
    D = 2 * alpha
    Pmax = 2 * (VMAX - 1) + alpha
    for shift in range(16, 62):
        recip = (1 << shift) // D + 1  # ceil(2^shift / D)
        bias = alpha * recip
        # int64 safety: max operand 2*(VMAX-1)*recip + bias must be < 2^63
        if 2 * (VMAX - 1) * recip + bias >= (1 << 63):
            continue
        ok = True
        # exhaustive check over the reachable range
        for v in range(0, VMAX):
            if ((2 * v * recip + bias) >> shift) != round_half_away(v, alpha):
                ok = False
                break
        if ok:
            return recip, shift, bias
    raise RuntimeError(f"no magic found for alpha={alpha}")


ALPHAS = {
    128: (90, 10, 5),
    256: (135, 5, 5),
    512: (144, 3, 3),
}
ALPHA_H = {128: 1024, 256: 1024, 512: 2048}


def log2_exact(x):
    assert x & (x - 1) == 0, x
    return x.bit_length() - 1


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "rounding_consts.h")
    logdir = os.path.join(here, "log")
    os.makedirs(logdir, exist_ok=True)
    logpath = os.path.join(logdir, "rounding_derivation.txt")

    lines = []
    log = []
    log.append("gen_rounding.py -- CompressY ties-away magic reciprocals")
    log.append(f"Exhaustively verified exact for 0 <= |v| < 2^20 = {VMAX}.")
    log.append("Kernel: qabs = (2*|v|*RECIP + ROUND_BIAS) >> SHIFT")
    log.append("        == round_half_away(|v|, alpha) = floor((2|v|+alpha)/(2 alpha))")
    log.append("")

    lines.append("/* rounding_consts.h -- AUTO-GENERATED by tools/gen_rounding.py.")
    lines.append(" * Division-free round-to-nearest (ties away from zero) magic")
    lines.append(" * reciprocals for CompressY (alpha_1/alpha_s/alpha_e) + the alpha_h")
    lines.append(" * highbits shift.  Verified exact for |v| < 2^20.  DO NOT hand-edit;")
    lines.append(" * regenerate via `python3 tools/gen_rounding.py`. */")
    lines.append("#ifndef SHUTTLE_ROUNDING_CONSTS_H")
    lines.append("#define SHUTTLE_ROUNDING_CONSTS_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append('#include "params.h"')
    lines.append("")

    for mode in (128, 256, 512):
        a1, asec, ae = ALPHAS[mode]
        log.append(f"=== SHUTTLE-{mode} ===")
        lines.append(f"#if SHUTTLE_MODE == {mode}")
        for name, alpha in (("1", a1), ("S", asec), ("E", ae)):
            recip, shift, bias = find_magic(alpha)
            log.append(f"  alpha_{name} = {alpha}: RECIP={recip} SHIFT={shift} "
                       f"ROUND_BIAS={bias}  (2*alpha={2*alpha})")
            lines.append(f"#    define RCP_ALPHA_{name} INT64_C({recip}) "
                         f"/* alpha={alpha}: ceil(2^{shift}/(2*alpha)) */")
            lines.append(f"#    define SH_ROUND_{name} {shift}")
            lines.append(f"#    define ROUND_BIAS_{name} INT64_C({bias}) "
                         f"/* = alpha*RECIP (folds the +alpha/2 tie bias) */")
        lh = log2_exact(ALPHA_H[mode])
        lines.append(f"#    define LOG2_ALPHA_H {lh} /* alpha_h={ALPHA_H[mode]} = 1<<{lh} */")
        lines.append("#endif")
        lines.append("")
        log.append(f"  alpha_h = {ALPHA_H[mode]}: LOG2_ALPHA_H = {lh}")
        log.append("")

    lines.append("/* Cross-check: alpha_h must be the power of two LOG2_ALPHA_H encodes. */")
    lines.append("_Static_assert(ALPHA_H == (1 << LOG2_ALPHA_H),")
    lines.append('               "alpha_h must equal 1 << LOG2_ALPHA_H");')
    lines.append("_Static_assert((ALPHA_B & (ALPHA_B - 1)) == 0,")
    lines.append('               "alpha_b must be a power of two");')
    lines.append("")
    lines.append("#endif /* SHUTTLE_ROUNDING_CONSTS_H */")

    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    with open(logpath, "w") as f:
        f.write("\n".join(log) + "\n")
    print("\n".join(log))
    print(f"Wrote {out}")
    print(f"Wrote audit log {logpath}")


if __name__ == "__main__":
    main()
