/* rounding_consts.h -- AUTO-GENERATED by tools/gen_rounding.py.
 * Division-free round-to-nearest (ties away from zero) magic
 * reciprocals for CompressY (alpha_1/alpha_s/alpha_e) + the alpha_h
 * highbits shift.  Verified exact for |v| < 2^20.  DO NOT hand-edit;
 * regenerate via `python3 tools/gen_rounding.py`. */
#ifndef SHUTTLE_ROUNDING_CONSTS_H
#define SHUTTLE_ROUNDING_CONSTS_H

#include <stdint.h>

#include "params.h"

#if SHUTTLE_MODE == 128
#    define RCP_ALPHA_1 INT64_C(1491309) /* alpha=90: ceil(2^28/(2*alpha)) */
#    define SH_ROUND_1 28
#    define ROUND_BIAS_1 INT64_C(134217810) /* = alpha*RECIP (folds the +alpha/2 tie bias) */
#    define RCP_ALPHA_S INT64_C(838861) /* alpha=10: ceil(2^24/(2*alpha)) */
#    define SH_ROUND_S 24
#    define ROUND_BIAS_S INT64_C(8388610) /* = alpha*RECIP (folds the +alpha/2 tie bias) */
#    define RCP_ALPHA_E INT64_C(838861) /* alpha=5: ceil(2^23/(2*alpha)) */
#    define SH_ROUND_E 23
#    define ROUND_BIAS_E INT64_C(4194305) /* = alpha*RECIP (folds the +alpha/2 tie bias) */
#    define LOG2_ALPHA_H 10 /* alpha_h=1024 = 1<<10 */
#endif

#if SHUTTLE_MODE == 256
#    define RCP_ALPHA_1 INT64_C(1988411) /* alpha=135: ceil(2^29/(2*alpha)) */
#    define SH_ROUND_1 29
#    define ROUND_BIAS_1 INT64_C(268435485) /* = alpha*RECIP (folds the +alpha/2 tie bias) */
#    define RCP_ALPHA_S INT64_C(838861) /* alpha=5: ceil(2^23/(2*alpha)) */
#    define SH_ROUND_S 23
#    define ROUND_BIAS_S INT64_C(4194305) /* = alpha*RECIP (folds the +alpha/2 tie bias) */
#    define RCP_ALPHA_E INT64_C(838861) /* alpha=5: ceil(2^23/(2*alpha)) */
#    define SH_ROUND_E 23
#    define ROUND_BIAS_E INT64_C(4194305) /* = alpha*RECIP (folds the +alpha/2 tie bias) */
#    define LOG2_ALPHA_H 10 /* alpha_h=1024 = 1<<10 */
#endif

#if SHUTTLE_MODE == 512
#    define RCP_ALPHA_1 INT64_C(233017) /* alpha=144: ceil(2^26/(2*alpha)) */
#    define SH_ROUND_1 26
#    define ROUND_BIAS_1 INT64_C(33554448) /* = alpha*RECIP (folds the +alpha/2 tie bias) */
#    define RCP_ALPHA_S INT64_C(699051) /* alpha=3: ceil(2^22/(2*alpha)) */
#    define SH_ROUND_S 22
#    define ROUND_BIAS_S INT64_C(2097153) /* = alpha*RECIP (folds the +alpha/2 tie bias) */
#    define RCP_ALPHA_E INT64_C(699051) /* alpha=3: ceil(2^22/(2*alpha)) */
#    define SH_ROUND_E 22
#    define ROUND_BIAS_E INT64_C(2097153) /* = alpha*RECIP (folds the +alpha/2 tie bias) */
#    define LOG2_ALPHA_H 11 /* alpha_h=2048 = 1<<11 */
#endif

/* Cross-check: alpha_h must be the power of two LOG2_ALPHA_H encodes. */
_Static_assert(ALPHA_H == (1 << LOG2_ALPHA_H),
               "alpha_h must equal 1 << LOG2_ALPHA_H");
_Static_assert((ALPHA_B & (ALPHA_B - 1)) == 0,
               "alpha_b must be a power of two");

#endif /* SHUTTLE_ROUNDING_CONSTS_H */
